branch-defaults:
  default:
    environment: Anecgame-env-1
environment-defaults:
  Anecgame-env-1:
    branch: null
    repository: null
global:
  application_name: AnecGame
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
